### ISSUE TITLE
Matching Credential Template Variables and CSV Upload

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#10]
Currently, the first example csv file provided by Tec is being used and the column names have been hard-coded into the system. 

The csv file that will be uploaded to a batch should contain the data that will populate the variables in the credential template being used for that batch. The columns provided should match the variable names to accommodate this.

We should discuss what happens if they don't match - perhaps a warning is displayed? Probably for now, it would be easiest to require that all variables be populated.

**Comment by goblincore** [comment]
@kayaelle We will add additional info about the fields (CSV vs those found in template). Currently the credential values are derived from the csv column names (EG they are not tied to the example csv) but there area few that are 'hard coded' for now, but we can talk more about this in our next meeting.

**Comment by TaylorBeeston** [comment]
@kayaelle as of https://github.com/learningeconomy/admin-dashboard/commit/b7b56d4aab4a7072f9483922039de129bf77d0bf we now display a warning/error if there is a mismatch between the template fields and CSV like this:

![image](https://github.com/learningeconomy/admin-dashboard/assets/39720479/b4dcbbd4-de0e-4da1-a445-9015cefde53a)

It's not in yet, but we're also going to add in the same warnings for the email template, and we'll add validation so that you can't issue a batch if the templates are expecting fields that aren't in the CSV!

**Comment by kayaelle** [comment]
This awesome! Thank you!

**Comment by kayaelle** [comment]
I think this issue is resolved generally but I submitted a few others about state of message display and alignment with the generated csv file and special fields.
