### ISSUE TITLE
Deletion of credentials and batches question

### ISSUE THREAD

**Issue by kayaelle** [learningeconomy/admin-dashboard#14]
What are the implications and consequences if credentials and batches are deleted? Does delete == revoked? Should we do an archive instead?

**Comment by TaylorBeeston** [comment]
I believe (need to verify) that this is currently an outstanding bug, and that what we should do on credential/batch deletion is exactly as you say, just revoke and archive rather than actually delete it! Right now I'm pretty sure it will just delete that object in Mongo without doing any revocation and will actually remove the ability to revoke if you deleted a credential 💀

**Comment by kayaelle** [comment]
Can we leave this one open for discussion at our next meeting so DCC team can chime in?

**Comment by TaylorBeeston** [comment]
@kayaelle Yup! For now I've updated permissions so that batches/credentials can only be deleted if they are in the draft state, so the immediate huge issue is closed for now!

**Comment by kayaelle** [comment]
Thanks @TaylorBeeston !
